server:
  port: 8080
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
    mvc:
           view:
               prefix: /WEB-INF/jsp/
               suffix: .jsp
    #thymeleaf模板
    thymeleaf:
        cache: false
        enabled: false #使用jsp需設置成false，使用thymeleaf 刪除即可
#        prefix: classpath:/templates/
#        suffix: .html
#        encoding: UTF-8
#        content-type: text/html
#        mode: HTML5
    datasource:
        name: test
        url: jdbc:mysql://47.93.16.203:3306/qjc
        username: root
        password: ruizhihudong
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.qjc.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

